### ISSUE TITLE
Play video inside a Div

### ISSUE THREAD

**Issue by ullasmohan** [Glitchbone/CordovaYoutubeVideoPlayer#15]
Hai Guys,

Is there any option for play a youtube video inside a Div element? just like youtube app?

please suggest..

**Comment by codeHatcher** [comment]
Why not just use the normal youtube embed code for this?

**Comment by Glitchbone** [comment]
Yes, you don't need this plugin for this

**Comment by ullasmohan** [comment]
Thank You.. Guys..

Its working :-)
