### ISSUE TITLE
Can't Play this Video

### ISSUE THREAD

**Issue by djsanj007** [Glitchbone/CordovaYoutubeVideoPlayer#34]
I am getting error in Android 5+ "Can't Play video" works fine in Samsung Device but fail in other Android Device.
I tried adding the YouTubeApiKey in the Config.xml but still issue persist
Please suggest.

**Comment by sanjib-dev** [comment]
use this
[https://github.com/JonSmart/CordovaYoutubeVideoPlayer](url)

**Comment by djsanj007** [comment]
@sanjib-dev 
I tried to add the provided plugin earlier as it is also provided on the Ionic Native Page, But adding it via cordova/ionic plugin add command returns following error
'Error: Failed to fetch plugin https://github.com/JonSmart/CordovaYoutubeVideoPlayer via registry.
Probably this is either a connection problem, or plugin spec is incorrect.'



I also tried to manually download the repositry & add it via add plugin via local, but the package.json was not there in the downloaded zip from
https://github.com/JonSmart/CordovaYoutubeVideoPlayer

**Comment by sanjib-dev** [comment]
It can be a project specific issue and yes if your Internet connection is
not stable it will not add to project which I also have faced.
Try to create a new one and try it out

**Comment by djsanj007** [comment]
Hi @sanjib-dev, I tried again with the fresh new Ionic 2 Project, but still the same issue persist, I tried to add the same plugin on three different-2 machines, I am able to add other plugin listed on Ionic/Native page, but facing issue with this plugin, I tried Network Information, InAppBrowser all are getting added but not this one :(
Are you able to add this plugin into your Ionic 2 project?

**Comment by sanjib-dev** [comment]
Yes.. Using this plug in in my project.
No such issues faced.

**Comment by djsanj007** [comment]
Can you send me the folder added in the Plugins folder of the project & entry in the fetch.json file!!?

**Comment by djsanj007** [comment]
What is the name of the plugin show while run the Ionic Plugin list command in the terminal

**Comment by djsanj007** [comment]
@sanjib-dev I figured it out, I was using Cordova version 7.0.1, & It expect package.json in the plugin  code, the current repo didn't have the package.json, so i forked the branch & added package.json in it, & added it using the same command
Now it work for older cordova version package.json was not mandatory in the plugin, that's why it was working fine for many user
