### ISSUE TITLE
Unable to hear Voice when playing in iOS

### ISSUE THREAD

**Issue by itskrsna** [Glitchbone/CordovaYoutubeVideoPlayer#36]
Can able to play this Plugin in Android,

When playing in iOS , unable to hear the voice .

**Comment by tjwoon** [comment]
Is your iPhone / iPad in Silent mode (ringer)? Your app may be using the Ringer volume instead of the Media volume.

Try this plugin to switch to the Media volume: https://www.npmjs.com/package/cordova-plugin-iosmediavolume

**Comment by itskrsna** [comment]
Yes, that is the issue ... solved the Issue
