### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by tolgatasci** [Glitchbone/CordovaYoutubeVideoPlayer#41]
cordova plugin add https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git -save
Error: Failed to fetch plugin https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/nc/fk4zxcg13w99jjkjfcv_1p3h0000gn/T/npm-999-204fbc80/git-cache-c507cd5d/765b5954e78ecf7950099c10bfe5f81133f8f396
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git" "--production" "--save"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/Desktop/cicimuzik/cicimuzik/npm-debug.log

**Comment by diegodotta** [comment]
This fork is working: https://github.com/denisx304/CordovaYoutubeVideoPlayer
